sudo: required
dist: trusty
language: node_js
node_js:
- "6"

addons:
  firefox: "50.0"

cache:
  directories:
  - node_modules
  - /usr/local/lib/node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm run build -s
  - npm run test -s
  - npm run lint -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
  #- npm run semantic-release
