sudo: required
dist: trusty
language: node_js
node_js: "6"
env:
  - NODE_ENV=ci

cache:
  directories:
  - node_modules
  - jspm_packages
  - /usr/local/lib/node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm i -g gulp typings jspm yarn

install:
  - yarn
  - jspm install
  - typings install

script:
  - npm run compile -s
  - npm run test -s
  - npm run lint -s
  - npm run build -s

#after_success:
#  - npm run semantic-release
