dist: trusty
language: node_js
services: docker

node_js:
- "12"

before_install:
  - npm install -g greenkeeper-lockfile@1
  - npm i @semantic-release/exec

before_script: greenkeeper-lockfile-update

script:
  - npm run build -s
  - npm run test -s
  - npm run lint -s
  - docker build . -t fossapps/handlebar-templates
  - npx semantic-release

after_success:
  - bash <(curl -s https://codecov.io/bash)
